#ifndef __wxTpGUIMainFrame__
#define __wxTpGUIMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "wxTpGUI.h"

//// end generated include

/** Implementing MainFrame */
class wxTpGUIMainFrame : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void MainFrameOnActivate( wxActivateEvent& event );
		void MainFrameOnClose( wxCloseEvent& event );
		void m_menuItemExitOnMenuSelection( wxCommandEvent& event );
		void m_menuItemAboutOnMenuSelection( wxCommandEvent& event );
	public:
		/** Constructor */
		wxTpGUIMainFrame( wxWindow* parent );
	//// end generated class members

};

#endif // __wxTpGUIMainFrame__
