#pragma once

// Header of the GUI class which is generated by builder
#include "buildergen/TpGUI.h"

#include "notepad/Notepad.h"

class TpMainFrame : public MainFrame {
   protected:
    Notepad m_notepad;
    
    void MainFrameOnClose(wxCloseEvent& event);

    bool OpenFileDialog();
    bool SaveFileDialog();
    bool FontDialog();

    bool SetClipboard(const wxString& text);
    wxString GetClipboard();
    
    void m_ribbonOnClick(wxRibbonButtonBarEvent& event);
    void m_ribbonToggleTheme(wxCommandEvent& event);

   public:
    TpMainFrame(wxWindow* parent);
};