#pragma once

// Header of the GUI class which is generated by builder
#include "buildergen/wxTpGUI.h"

#include "../notepad/Notepad.h"

class wxTpGUIMainFrame : public MainFrame {
   protected:
    Notepad m_notepad;
    
    void MainFrameOnClose(wxCloseEvent& event);

    bool OpenFile();
    bool SaveFile();

    void m_menuItemOpenOnMenuSelection(wxCommandEvent& event);
    void m_menuItemSaveAsOnMenuSelection(wxCommandEvent& event);
    void m_menuItemExitOnMenuSelection(wxCommandEvent& event);
    void m_menuItemAboutOnMenuSelection(wxCommandEvent& event);

   public:
    wxTpGUIMainFrame(wxWindow* parent);
};